/**
 * WARNING: DO NOT TOUCH THIS FILE UNLESS YOU HAVE A VALID REASON
 */

const categories = [
  require('../assets/categoryIcons/Restaurant/anything.png'),
  require('../assets/categoryIcons/Restaurant/italian.png'),
  require('../assets/categoryIcons/Restaurant/mexican.png'),
  require('../assets/categoryIcons/Restaurant/korean.png'),
  require('../assets/categoryIcons/Restaurant/seafood.png'),
  require('../assets/categoryIcons/Restaurant/vegeterian.png'),
  require('../assets/categoryIcons/Restaurant/steakhouse.png'),
  require('../assets/categoryIcons/Restaurant/pizza.png'),
  require('../assets/categoryIcons/Restaurant/tacos.png'),
  require('../assets/categoryIcons/Restaurant/poke.png'),
  require('../assets/categoryIcons/Restaurant/japanese.png'),
  require('../assets/categoryIcons/Restaurant/vietnamese.png'),
  require('../assets/categoryIcons/Restaurant/chinese.png'),
  require('../assets/categoryIcons/Restaurant/thai.png'),
  require('../assets/categoryIcons/Restaurant/sushi-bars.png'),
  require('../assets/categoryIcons/Restaurant/american.png'),
  require('../assets/categoryIcons/Cafe-Desserts/cafe.png'),
  require('../assets/categoryIcons/Cafe-Desserts/ice-cream.png'),
  require('../assets/categoryIcons/Cafe-Desserts/bubble-tea.png'),
  require('../assets/categoryIcons/Cafe-Desserts/donuts.png'),
  require('../assets/categoryIcons/Cafe-Desserts/shaved-ice.png'),
  require('../assets/categoryIcons/Cafe-Desserts/crepe.png'),
  require('../assets/categoryIcons/Cafe-Desserts/gelato.png'),
  require('../assets/categoryIcons/Cafe-Desserts/waffle.png'),
  require('../assets/categoryIcons/Recreations/karaoke.png'),
  require('../assets/categoryIcons/Recreations/mini-golf.png'),
  require('../assets/categoryIcons/Recreations/arcade.png'),
  require('../assets/categoryIcons/Recreations/ice-skate.png'),
  require('../assets/categoryIcons/Recreations/bowling.png'),
  require('../assets/categoryIcons/Recreations/escape-room.png'),
  require('../assets/categoryIcons/Recreations/movie.png'),
  require('../assets/categoryIcons/Recreations/museum.png'),
  require('../assets/categoryIcons/Recreations/casino.png'),
  require('../assets/categoryIcons/Recreations/laser-tag.png'),
  require('../assets/categoryIcons/Outdoors/park.png'),
  require('../assets/categoryIcons/Outdoors/hiking-trail.png'),
  require('../assets/categoryIcons/Outdoors/view-point.png'),
  require('../assets/categoryIcons/Outdoors/beach.png'),
  require('../assets/categoryIcons/Outdoors/waterfall.png'),
  require('../assets/categoryIcons/Outdoors/botanical-garden.png'),
  require('../assets/categoryIcons/Shopping/shopping-center.png'),
  require('../assets/categoryIcons/Shopping/shopping-center.png'),
  require('../assets/categoryIcons/Shopping/bookstore.png'),
  require('../assets/categoryIcons/Shopping/antique-shop.png'),
  require('../assets/categoryIcons/Shopping/thrift-store.png'),
  require('../assets/categoryIcons/Night-Life/bars.png'),
  require('../assets/categoryIcons/Night-Life/night-clubs.png'),
  require('../assets/categoryIcons/Night-Life/pool-bars.png'),
  require('../assets/categoryIcons/Night-Life/pubs.png'),
  require('../assets/categoryIcons/Night-Life/sports-bars.png'),
];

export default categories;
