const icons = {
  add: require('../assets/icons/add.png'),
  back: require('../assets/icons/back.png'),
  bell: require('../assets/icons/bell.png'),
  bookmark: require('../assets/icons/bookmark.png'),
  bookmarked: require('../assets/icons/bookmarked.png'),
  call: require('../assets/icons/call.png'),
  chat: require('../assets/icons/chat.png'),
  checked: require('../assets/icons/checked.png'),
  clock: require('../assets/icons/clock.png'),
  close: require('../assets/icons/x.png'),
  drag: require('../assets/icons/drag.png'),
  drop: require('../assets/icons/drop.png'),
  edit: require('../assets/icons/edit.png'),
  expand: require('../assets/icons/expand.png'),
  friends: require('../assets/icons/friends.png'),
  heart: require('../assets/icons/heart.png'),
  hearted: require('../assets/icons/hearted.png'),
  history: require('../assets/icons/history.png'),
  like: require('../assets/icons/like.png'),
  map: require('../assets/icons/map.png'),
  minus: require('../assets/icons/minus.png'),
  more: require('../assets/icons/more.png'),
  open: require('../assets/icons/open.png'),
  option: require('../assets/icons/option.png'),
  pin: require('../assets/icons/pin.png'),
  placeholder: require('../assets/icons/placeholder.png'),
  question: require('../assets/icons/question.png'),
  roulette: require('../assets/icons/roulette.png'),
  search: require('../assets/tabIcons/search-2.png'),
  selected: require('../assets/icons/selected.png'),
  settings: require('../assets/icons/settings.png'),
  shrink: require('../assets/icons/shrink.png'),
  unchecked: require('../assets/icons/unchecked.png'),
  unselected: require('../assets/icons/unselected.png'),
};

export default icons;
