const strings = {
  main: {
    appName: 'Planet',
    share: 'Share',
    none: 'None',
    save: 'Save',
    done: 'Done',
    cancel: 'Cancel',
    discard: 'Discard',
    edit: 'Edit',
    remove: 'Remove',
    rename: 'Rename',
    add: 'Add',
    create: 'Create',
    next: 'Next',
    back: 'Back',
    search: 'Search',
    seeAll: 'See All',
    milesAbbrev: 'mi',
    dash: '-',
    warning: 'Warning',
  },
  login: {
    login: 'Login',
    forgotPassword: 'Forgot Password?',
    noAccount: "Don't have an account?",
    signUp: 'Sign up',
    email: 'Email',
    password: 'Password',
    missingInfo: 'Missing email or password',
  },
  signUp: {
    name: 'Name',
    confirmPassword: 'Confirm Password',
    phoneNumber: 'Phone Number',
    signUp: 'Sign Up',
    termsAgreement:
      "By signing up, you agree to Rivalet's Terms and Conditions and Privacy Policy.",
    passwordsMatch: 'Passwords are not the same',
    missingFields: 'Fields are missing',
  },
  poi: {
    createEvent: 'Create an Event',
    unbookmark: 'Unbookmark',
    bookmark: 'Bookmark',
    openMap: 'Open map',
    eventUrl: 'Website',
    description: 'Description',
    address: 'Address',
    hours: 'Hours',
    phone: 'Phone',
    url: 'URL',
    website: 'Website',
    attributes: 'Attributes',
  },
  search: {
    search: 'Search',
    noResultsFound: 'No Results Found',
    noResultsFoundDescription: 'Try searching for something else',
    setLocation: 'Set Location',
    tooFar: 'Radius too large',
    tooFarMessage: 'Please select a smaller radius',
  },
  greeting: {
    welcome: 'Welcome',
    morning: 'Good Morning',
    afternoon: 'Good Afternoon',
    evening: 'Good Evening',
  },
  friends: {
    friends: 'Friends',
  },
  profile: {
    yourProfile: 'Your Profile',
    bookmarks: 'Bookmarks',
    yourAlbums: 'Your Albums',
    settings: 'Settings',
    noBookmarksFound: 'No Bookmarks Found',
    noBookmarksFoundDescription: 'Try bookmarking something',
  },
  event: {
    untitled: 'Untitled Event',
    backConfirmation:
      'Are you sure you want to go back? Your event will not be saved.',
    addDestination: 'Add a Destination',
    moveUp: 'Move Up',
    moveDown: 'Move Down',
    renamePrompt: 'Enter a new name for this destination:',
  },
};

export default strings;
