const strings = {
  main: {
    rivalet: 'Rivalet',
    done: 'Done',
    save: 'Save',
    images: 'Images',
    dash: '-',
    notApplicable: 'N/A',
  },
  login: {
    login: 'Login',
    forgotPassword: 'Forgot Password?',
    noAccount: "Don't have an account?",
    signUp: 'Sign up',
    email: 'Email',
    password: 'Password',
    missingInfo: 'Missing email or password',
  },
  signUp: {
    name: 'Name',
    confirmPassword: 'Confirm Password',
    phoneNumber: 'Phone Number',
    age: 'Age (optional)',
    signUp: 'Sign Up',
    termsAgreement:
      "By signing up, you agree to Rivalet's Terms and Conditions and Privacy Policy.",
    passwordsMatch: 'Passwords are not the same',
    missingFields: 'Fields are missing',
  },
  createTabStack: {
    milesAbbrev: 'mi',
    planEvent: 'Choose a Location',
    search: 'Search',
    selectCategories: 'Select Categories',
    selectDestinations: 'Select Destinations',
    radius: 'Radius',
    recreation: 'Recreation',
    experience: 'Experience',
    shopping: 'Shopping',
    outdoors: 'Outdoors',
    restaurants: 'Restaurants',
    sweets: 'Sweets',
    selectedCategories: 'Selected Categories',
    untitledEvent: 'Untitled Event',
    pickDate: 'Pick a date',
    hours: 'Hours',
    address: 'Address',
    rating: 'Rating',
    wheelchair: 'Wheelchair Accessible',
    creditCard: 'Accepts credit card',
    streetParking: 'Street Parking',
    price: 'Price',
    rnr: 'Ratings & Reviews',
    events: 'Events',
    details: 'Details',
    noDestinations: 'No Destinations Found',
    saveEvent: 'Save an Event',
    name: 'Name',
    date: 'Date',
    cancel: 'Cancel',
    confirm: 'Confirm',
    venue: 'Event Venue',
    eventTime: 'Event Time',
    eventStatus: 'Event Status',
    eventSpan: 'Event spans multiple days',
    eventUrl: 'Tap for more information',
  },
  settings: {
    name: 'Name',
    username: 'UserName',
    resetPassword: 'Reset Password',
    upgrade: 'Upgrade to Premium',
    logout: 'Log out',
  },
  title: {
    trending: 'Trending',
    friends: 'Friends',
    library: 'Library',
    profile: 'Profile',
    settings: 'Settings',
  },
  library: {
    saved: 'Saved',
    events: 'Events',
  },
  profile: {
    followers: 'followers',
    following: 'following',
  },
  trending: {
    in: 'in',
    seeAll: 'See All',
  },
  filter: {
    all: 'All Categories',
    within: 'Within',
    inTheNext: 'In the Next',
    sortby: 'Sort By',
    editView: 'Edit View',
    visible: 'Visible',
    hidden: 'Hidden',
  },
  misc: {
    maxRating: '5',
  },
};

export default strings;
